version: "2"
checks:
  method-complexity:
    config:
      threshold: 8
  method-lines:
    config:
      threshold: 150
  similar-code:
    enabled: false
  identical-code:
    enabled: true
exclude_patterns:
- "**/*.md"
- "cypress/"
- "public/"
- "src/guides/"
