version: "2"
checks:
  method-complexity:
    config:
      threshold: 5
  method-lines:
    config:
      threshold: 100
  similar-code:
    enabled: false
  identical-code:
    enabled: true
exclude_patterns:
- "**/*.md"
- "cypress/"
- "public/"
- "src/guides/"
plugins: 
  eslint:
    enabled: true
    channel: "eslint-6"
