version: "2"
checks:
  method-complexity:
    config:
      threshold: 5
  method-lines:
    config:
      threshold: 50
exclude_patterns:
- "cypress/*"
plugins: 
  eslint:
    enabled: true
    channel: "eslint-6"